### ISSUE TITLE
Need All Features..

### ISSUE THREAD

**Issue by rambabupudari** [SteadfastInnovation/libhpdf-AndroidLibrary#1]
Hi,
Can u please update the library for android with  all features in libharu.

we need all feature what ever contain in libharu.its very much helpfull to create the pdf with text,borders,images....

Thanks in Advance.

**Comment by ashughes** [comment]
We are no longer using libharu for PDF generation, so I won't be working on updating this library. We are now using the excellent PDF library at http://www.androidpdf.mobi.

However I'd gladly accept pull requests!
